#!/bin/bash
set -e

EVIDENCE_DIR="deployment-evidence-$(date +%Y%m%d-%H%M%S)"
mkdir -p "$EVIDENCE_DIR"

echo "Capturing deployment evidence..."

# 1. Capture Docker containers status
echo "Capturing container status..."
docker ps -a > "$EVIDENCE_DIR/containers-status.txt"
docker compose ps > "$EVIDENCE_DIR/compose-status.txt"

# 2. Capture logs
echo "Capturing logs..."
docker compose logs backend > "$EVIDENCE_DIR/backend-logs.txt" 2>&1
docker compose logs frontend > "$EVIDENCE_DIR/frontend-logs.txt" 2>&1
docker compose logs db > "$EVIDENCE_DIR/db-logs.txt" 2>&1

# 3. Capture health checks
echo "Checking health endpoints..."
curl -s http://localhost:8080/actuator/health > "$EVIDENCE_DIR/backend-health.json" || echo "Backend health check failed"
curl -s http://localhost:80/health > "$EVIDENCE_DIR/frontend-health.txt" || echo "Frontend health check failed"

# 4. Capture network info
echo "Capturing network configuration..."
docker network inspect ecommerce-frontend_app-network > "$EVIDENCE_DIR/network-config.json" 2>&1 || true

# 5. Capture environment info
echo "Capturing environment..."
docker compose config > "$EVIDENCE_DIR/docker-compose-resolved.yml"

# 6. Take screenshots (requires Chrome/Chromium)
if command -v chromium &> /dev/null; then
    echo "Taking screenshots..."
    chromium --headless --screenshot="$EVIDENCE_DIR/frontend-homepage.png" http://localhost:80 2>&1 || true
fi

# 7. Generate summary report
echo "Generating summary report..."
cat > "$EVIDENCE_DIR/DEPLOYMENT-SUMMARY.md" <<EOF
# Deployment Evidence Report

**Date**: $(date)
**Deployment ID**: $(date +%Y%m%d-%H%M%S)

## Container Status
\`\`\`
$(docker compose ps)
\`\`\`

## Health Checks
- Backend: $(curl -s http://localhost:8080/actuator/health | jq -r '.status' 2>/dev/null || echo "FAILED")
- Frontend: $(curl -s -o /dev/null -w "%{http_code}" http://localhost:80 2>/dev/null || echo "FAILED")
- Database: $(docker exec mysql_db mysqladmin ping -h localhost -uroot -p${MYSQL_ROOT_PASSWORD} 2>/dev/null | grep -q "alive" && echo "UP" || echo "DOWN")

## Services Running
- Frontend: http://localhost:80
- Backend: http://localhost:8080
- Database: localhost:3306

## Files Captured
- Container status logs
- Application logs (backend, frontend, database)
- Health check responses
- Network configuration
- Docker Compose resolved configuration
$([ -f "$EVIDENCE_DIR/frontend-homepage.png" ] && echo "- Screenshot of homepage")

## Next Steps
1. Review logs in: $EVIDENCE_DIR/
2. Verify all health checks are passing
3. Test application functionality
4. Monitor for 24 hours

---
Generated by deployment evidence script
EOF

echo "Evidence captured in: $EVIDENCE_DIR/"
echo "View summary: $EVIDENCE_DIR/DEPLOYMENT-SUMMARY.md"

# Create archive
tar -czf "${EVIDENCE_DIR}.tar.gz" "$EVIDENCE_DIR"
echo "Archive created: ${EVIDENCE_DIR}.tar.gz"
# ===========================================
# MAKEFILE FOR EASY DEPLOYMENT
# ===========================================
# Makefile

.PHONY: help build up down logs test evidence clean

help:
	@echo "Available commands:"
	@echo "  make build     - Build Docker images"
	@echo "  make up        - Start all services"
	@echo "  make down      - Stop all services"
	@echo "  make logs      - View logs"
	@echo "  make test      - Run tests"
	@echo "  make evidence  - Capture deployment evidence"
	@echo "  make clean     - Clean up containers and volumes"

build:
	docker compose build --no-cache

up:
	docker compose up -d
	@echo "Waiting for services to be healthy..."
	@sleep 30
	@make evidence

down:
	docker compose down

logs:
	docker compose logs -f

test:
	@echo "Running backend tests..."
	cd ecommerce-backend/ecommerce-backend && ./mvnw test
	@echo "Running frontend tests..."
	cd ecommerce-frontend && npm run test:run

evidence:
	@chmod +x scripts/capture-deployment-evidence.sh
	@./scripts/capture-deployment-evidence.sh

clean:
	docker compose down -v
	docker system prune -f